---
- name: Combine go-carbon config with defaults
  set_fact: go_carbon_conf="{{ go_carbon_conf_defaults | combine(go_carbon_conf,recursive=True)}}"

- name: Create storage directory
  file:
    path: "{{ go_carbon_conf.whisper['data-dir'] }}"
    state: directory
    owner: "{{ go_carbon_conf.common.user }}"
    group: "{{ go_carbon_conf.common.group }}"
    mode: 0775
    recurse: yes
  
- name: Create tags directory
  file:
    path: "{{ go_carbon_conf.tags['local-dir'] }}"
    state: directory
    owner: "{{ go_carbon_conf.common.user }}"
    group: "{{ go_carbon_conf.common.group }}"
    mode: 0775
    recurse: yes

- name: Create dump directory
  file:
    path: "{{ go_carbon_conf.dump.path }}"
    state: directory
    owner: "{{ go_carbon_conf.common.user }}"
    group: "{{ go_carbon_conf.common.group }}"
    mode: 0775
    recurse: yes

- name: Copy go-carbon.conf
  template:
    src: go-carbon.conf.j2
    dest: "{{ go_carbon_config_file }}"
    owner: "{{ go_carbon_conf.common.user }}"
    group: "root"
    mode: 0600
  notify: restart go-carbon service

  # schemas and aggregations are automatically reloaded every 60 seconds
- name: "Copy storage schemas"
  template:
    src: storage-schemas.conf.j2
    dest: "{{ go_carbon_conf.whisper['schemas-file'] }}"
    owner: "{{ go_carbon_conf.common.user }}"
    group: "root"
    mode: 0600

- name: "Copy storage aggregation"
  template:
    src: storage-aggregation.conf.j2
    dest: "{{ go_carbon_conf.whisper['aggregation-file'] }}"
    owner: "{{ go_carbon_conf.common.user }}"
    group: "root"
    mode: 0600
